title: 艾拉科技-专注于现代IT架构下的网络安全、商用密码应用
description: 艾拉信息科技有限公司主要经营现代IT架构下的信息安全类、密码应用科技创新产品，包括：快速测评辅助系统（快测）、商用密码应用与检测工具箱（密测工具箱）、支持新应用架构和协议的国密WEB应用安全网关（新渡网关）、支持国密算法的高性能零信任网络安全产品（飞镖网络）、蜜盾内网拟态防御系统（蜜盾盒子）、关键数据全生命周期安全管理系统（关键数据网关）。

# disabled because we are using a custom domain
#baseurl: /business-frontpage 

color-scheme: "mediumseagreen" # the scheme can be any HEX code like "#00aa55"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
